# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Astroclub
author: Astroclub Community
copyright: "2024"
logo: logo3.jpg

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force

# Define the name of the latex output file for PDF builds
latex:
  latex_engine: xelatex
  latex_documents:
    targetname: book.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

repository:
  url: https://github.com/FedorovVS/astroclub
  branch: master

html:
  use_issues_button: true
  use_repository_button: true
  baseurl: "https://astroclub.su/"
  extra_footer: Распространяется на условиях <a href="https://creativecommons.org/licenses/by-sa/4.0/deed.ru">лицензии Creative Commons Attribution-ShareAlike 4.0 International</a>.

sphinx:
  config:
    templates_path:
      - _templates
    myst_enable_extensions:
      - attrs_inline
      - colon_fence
      - dollarmath
      - linkify
      - substitution
      - tasklist
    numfig: True
    numfig_secnum_depth: 1
    numfig_format:
      code-block: "Listing %s"
      figure: "Рис. %s"
      section: "Section"
      table: "Таб. %s"
